- name: Install grafana
  kubernetes.core.helm:
    name: grafana
    namespace: kube-system
    chart_ref: ../charts/grafana
    kubeconfig_path: "{{ kubeconfig }}"
    create_namespace: True
    wait: true
